#ifndef IBCOLOR_H_
#define IBCOLOR_H_

#ifdef _WIN32
#include <Windows.h>
typedef enum IBColor {
	//fg
	IBFgWHITE = FOREGROUND_RED
	| FOREGROUND_GREEN
	| FOREGROUND_BLUE,
	IBFgRED = FOREGROUND_RED,
	IBFgGREEN = FOREGROUND_GREEN,
	IBFgBLUE = FOREGROUND_BLUE,
	IBFgYELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
	IBFgCYAN = FOREGROUND_BLUE | FOREGROUND_GREEN,
	IBFgMAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
	IBFgBROWN = FOREGROUND_RED | FOREGROUND_GREEN,
	IBFgIntensity = FOREGROUND_INTENSITY,

	//bg
	IBBgWHITE = BACKGROUND_RED
	| BACKGROUND_GREEN
	| BACKGROUND_BLUE,
	IBBgRED = BACKGROUND_RED,
	IBBgGREEN = BACKGROUND_GREEN,
	IBBgBLUE = BACKGROUND_BLUE,
	IBBgYELLOW = BACKGROUND_RED | BACKGROUND_GREEN,
	IBBgCYAN = BACKGROUND_BLUE | BACKGROUND_GREEN,
	IBBgMAGENTA = BACKGROUND_RED | BACKGROUND_BLUE,
	IBBgBROWN = BACKGROUND_RED | BACKGROUND_GREEN,
	IBBgIntensity = BACKGROUND_INTENSITY
}IBColor;
#else//unix soon
typedef enum IBColor {
	//fg
	IBFgWHITE,
	IBFgRED,
	IBFgGREEN,
	IBFgBLUE,
	IBFgYELLOW,
	IBFgCYAN,
	IBFgMAGENTA,
	IBFgBROWN,
	IBFgIntensity,

	//bg
	IBBgWHITE,
	IBBgRED,
	IBBgGREEN,
	IBBgBLUE,
	IBBgYELLOW,
	IBBgCYAN,
	IBBgMAGENTA,
	IBBgBROWN,
	IBBgIntensity
}IBColor;
#endif

void IBSetColor(IBColor col);
void IBPushColor(IBColor col);
void _IBVectorCopyPushIBColor(struct IBVector* vec, IBColor col,char*file,int ln);
#define IBVectorCopyPushIBColor(vec,col)\
	_IBVectorCopyPushIBColor(vec,col,__FILE__,__LINE__)
void IBPopColor();


#endif